%% Setup
load linearization; % load equilibrium conffiguration
                    % and matrices AA, BB, CC, DD

[V, D] = eig(AA);

lam = diag(D);

[~,ind] = sort(abs(lam)); % sort in increasing order of frequency

nDof = size(V,1)/2; % number of degrees of freedom (/2 to take only 
                    % displacement components

thet = pi/2+linspace(0,2*pi,101); % angle to rotate complex eigenvectors
expit = exp(1i*thet); 

addpath ..
                    
%% Look at a mode graphically
n = 15;
scale = 1000;
mode1 = X0 + scale*(2*real(V(:,ind(n))*expit));
[~, ~, P, ~] = ...
            Template2StructureDynamicsOutputs(thet, mode1', [], ...
                                                RJ_SA, RJ_B, ...
                                                x01_C, RE1_C, r1_C, ...
                                                x02_C, RE2_C, r2_C, ...
                                                Rb10, Rb20, ...
                                                N, Nbrev, ...
                                                maskSADof, maskBDof, ...
                                                indexSADof, indexBDof);
f = abs(lam(ind(n)))/2/pi;
xi = -real(lam(ind(n)))/abs(lam(ind(n)));
titlestr = sprintf('f = %.3f Hz; xi = %.3f', f, xi);
figure(501) % open a new figure, and pass its axis handle to QuickAndDirty
QuickAndDirtyAnimation(P(:,1),P-P(:,1),x0_SA,x0_B,knots,...
                       1,[1 -1 1],gca,titlestr);
                                            

%% Look at the mode numerically
X0_ = [X0(1:length(X0)/2); 2*real(V(1:length(X0)/2,ind(n)))];
[~, ~, P_, ~, ~, ~, Pdot_, ~] = ...
            Template2StructureDynamicsOutputs(0, X0_', [], ...
                                                RJ_SA, RJ_B, ...
                                                x01_C, RE1_C, r1_C, ...
                                                x02_C, RE2_C, r2_C, ...
                                                Rb10, Rb20, ...
                                                N, Nbrev, ...
                                                maskSADof, maskBDof, ...
                                                indexSADof, indexBDof);


%% 
rmpath ..

