function [drdz,drdzp] = BushingDynamicsJac(t, z, zp, ...
                                  m, II, kv, kr, cv, cr, h, g, thet0, ...
                                  ux, uz, dtsample)

% Same inputs as BushingDynamicsImplicit

[~,drdz,drdzp] = BushingDynamicsImplicit(t, z, zp, ...
                                m, II, kv, kr, cv, cr, h, g, thet0, ...
                                ux, uz, dtsample);
