function [Fb, Kb, Cb, Mb, Kb_FD, Cb_FD, Mb_FD] ...
       = CableRotBCinCoordStiffnessCheckFD(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic)
                    
% Check derivative matrices (stiffness, damping and mass) of cable with 
% rotation boundary conditions by finite differences
% inputs and outputs are same as CableForceRotBCinCoord

[Fb, Kb, Cb, Mb] ...
       = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
                     
epsilon = 1e-7;
Kb_FD = zeros(size(Kb));
Cb_FD = zeros(size(Cb));
Mb_FD = zeros(size(Mb));

I3 = eye(3);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Stiffness by finite differences
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
colKb = 0;
for k = 1:3 % perturb d1
    d1_ = d1 + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1_, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Kb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

for k = 1:3 % perturb phi1
    phi1_ = phi1 + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1_, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Kb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

% perturb gamm1
Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1+epsilon, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
colKb = colKb + 1;
Kb_FD(:,colKb) = (Fb_-Fb)/epsilon;

for k = 1:3 % perturb d2
    d2_ = d2 + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2_, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Kb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

for k = 1:3 % perturb phi2
    phi2_ = phi2 + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2_, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Kb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

% perturb gamm2
Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2+epsilon, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
colKb = colKb + 1;
Kb_FD(:,colKb) = (Fb_-Fb)/epsilon;

% perturb Pmid
for l = 1:size(Pmid,2)
  for k = 1:3 
    Pmid_ = Pmid;
    Pmid_(k,l) = Pmid_(k,l) + epsilon;
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid_, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Kb_FD(:,colKb) = (Fb_-Fb)/epsilon;
  end
end

% perturb varThetamid
for k = 1:length(varThetamid)
    varThetamid_ = varThetamid;
    varThetamid_(k) = varThetamid_(k) + epsilon;
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid_, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Kb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Damping by finite differences
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
colKb = 0;
for k = 1:3 % perturb d1dot
    d1dot_ = d1dot + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot_, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Cb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

for k = 1:3 % perturb phi1dot
    phi1dot_ = phi1dot + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot_, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Cb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

% perturb gamm1dot
Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot+epsilon, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
colKb = colKb + 1;
Cb_FD(:,colKb) = (Fb_-Fb)/epsilon;

for k = 1:3 % perturb d2dot
    d2dot_ = d2dot + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot_, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Cb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

for k = 1:3 % perturb phi2dot
    phi2dot_ = phi2dot + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot_, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Cb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

% perturb gamm2dot
Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot+epsilon, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
colKb = colKb + 1;
Cb_FD(:,colKb) = (Fb_-Fb)/epsilon;

% perturb Pmiddot
for l = 1:size(Pmid,2)
  for k = 1:3 
    Pmiddot_ = Pmiddot;
    Pmiddot_(k,l) = Pmiddot_(k,l) + epsilon;
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot_, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Cb_FD(:,colKb) = (Fb_-Fb)/epsilon;
  end
end

% perturb varThetamiddot
for k = 1:length(varThetamid)
    varThetamiddot_ = varThetamiddot;
    varThetamiddot_(k) = varThetamiddot_(k) + epsilon;
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot_, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Cb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Mass by finite differences
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
colKb = 0;
for k = 1:3 % perturb d1ddot
    d1ddot_ = d1ddot + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot_, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Mb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

for k = 1:3 % perturb phi1ddot
    phi1ddot_ = phi1ddot + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot_, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Mb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

% perturb gamm1ddot
Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot+epsilon, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
colKb = colKb + 1;
Mb_FD(:,colKb) = (Fb_-Fb)/epsilon;

for k = 1:3 % perturb d2ddot
    d2ddot_ = d2ddot + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot_, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Mb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

for k = 1:3 % perturb phi2ddot
    phi2ddot_ = phi2ddot + epsilon*I3(:,k);
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot_, gamm2ddot, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Mb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end

% perturb gamm2ddot
Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot+epsilon, ...
                         Pmidddot, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
colKb = colKb + 1;
Mb_FD(:,colKb) = (Fb_-Fb)/epsilon;

% perturb Pmidddot
for l = 1:size(Pmid,2)
  for k = 1:3 
    Pmidddot_ = Pmidddot;
    Pmidddot_(k,l) = Pmidddot_(k,l) + epsilon;
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot_, varThetamidddot, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Mb_FD(:,colKb) = (Fb_-Fb)/epsilon;
  end
end

% perturb varThetamidddot
for k = 1:length(varThetamid)
    varThetamidddot_ = varThetamidddot;
    varThetamidddot_(k) = varThetamidddot_(k) + epsilon;
    Fb_ = CableForceRotBCinCoord(d1, phi1, gamm1, ...
                         d2, phi2, gamm2, ...
                         Pmid, varThetamid, ...
                         P0, ...
                         d1dot, phi1dot, gamm1dot, ...
                         d2dot, phi2dot, gamm2dot, ...
                         Pmiddot, varThetamiddot, ...
                         d1ddot, phi1ddot, gamm1ddot, ...
                         d2ddot, phi2ddot, gamm2ddot, ...
                         Pmidddot, varThetamidddot_, ...
                         x01, RJ1, RE1, r1, ...
                         x02, RJ2, RE2, r2, ...
                         R0, II, ...
                         rho, EA, EI, GJ, betAX, betBEND, betTOR, ...
                         sg, wg, nel, ...
                         colmat, colmat_brev, colmat_bar, ...
                         d, dbrev, dbar, ...
                         Mbar, ...
                         u, ...
                         Kbar11, Dbar11, dynamic);
   colKb = colKb + 1;
   Mb_FD(:,colKb) = (Fb_-Fb)/epsilon;
end